foreground   #e4eeff
background   #0c0a20
cursor       #e4eeff

color0       #0c0a20
color1       #ff2e97
color2       #62a9cf
color3       #ffd400
color4       #42c6ff
color5       #ff2afc
color6       #42c6ff
color7       #d9e0e9
color8       #435056
color9       #ff2e97
color10      #add0e5
color11      #ffd400
color12      #42c6ff
color13      #ff2afc
color14      #42c6ff
color15      #f4f6f9
