# preload = /home/ltadeu6/Imagens/wallpaper/second-collection/spooky-minimal/dracula-spooky-44475a.png
preload = /home/ltadeu6/Imagens/wallpaper/first-collection/nixos.png
#if more than one preload is desired then continue to preload other backgrounds

#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
# wallpaper = , /home/ltadeu6/Imagens/wallpaper/second-collection/spooky-minimal/dracula-spooky-44475a.png
wallpaper = , /home/ltadeu6/Imagens/wallpaper/first-collection/nixos.png

splash = false
